### ISSUE TITLE
Where do repository icons come from?

### ISSUE THREAD

**Issue by mberasategi** [education/classroom-assistant#107]
I'm just testing the Classroom Assistant and the repository listing shows an icon for each of them which has nothing to do with the actual repository. Where are those coming from?

**Comment by johndbritton** [comment]
The icon should be the avatar of the user, in the case that the user avatar is not set, GitHub provides an [Identicon](https://blog.github.com/2013-08-14-identicons/) which is a generated image to use in place of the avatar.

**Comment by mberasategi** [comment]
Thanks @johndbritton , but that's not what I'm seeing. 

![imagen](https://user-images.githubusercontent.com/738823/46674907-9b637e80-cbdd-11e8-8a6e-785b3e6abd3b.png)

No user in the repositories has those avatars. See the [list of contributors to the first one](https://github.com/DeustoPWEB2018/proyectoweb-ocio/graphs/contributors), for example:

![imagen](https://user-images.githubusercontent.com/738823/46675034-df568380-cbdd-11e8-8550-adf561f245e5.png)

**Comment by johndbritton** [comment]
You are viewing a group assignment, which according to https://github.com/education/classroom-assistant/issues/85 is unimplemented. Those avatars are incorrect.

Closing this in favor of #85 and updating there.
