### ISSUE TITLE
Only the first repo gets successfully cloned

### ISSUE THREAD

**Issue by mberasategi** [education/classroom-assistant#108]
Each time I've tried, only the first repository in the list gets cloned. The rest show the error message `Clone failed: Folder could not be created.`

**Comment by johndbritton** [comment]
Thanks for the report @mberasategi.

Can you please provide some more information?

* What operating system and version are you using?
* Can you provide a screenshot?
* Does this happen on all assignments or just this particular assignment?

**Comment by mberasategi** [comment]
OS is Windows 10 Pro v.1809. I don't have any other assignments to test at the moment, but it's been happening each time I've tried. 

Also, the error appears instantly, even before the first download starts.

![imagen](https://user-images.githubusercontent.com/738823/46675261-525ffa00-cbde-11e8-919c-5d3d420e3ed7.png)

**Comment by johndbritton** [comment]
@srinjoym Is this because of a race condition in https://github.com/education/classroom-assistant/blob/master/app/modules/submissions/actions/submission-clone-all.js?

**Comment by srinjoym** [comment]
Hey @mberasategi 👋 

Sorry you're hitting this issue! When you try to clone your assignment, which folder are you selecting as the `Archive Destination`?

<img width="1200" alt="screen shot 2018-10-10 at 11 49 08 am" src="https://user-images.githubusercontent.com/7866060/46752333-868cf680-cc82-11e8-9a28-cff2568bed1f.png">

@johndbritton We wait for the folder to be created before we try and clone the assignment, if the folder fails to be created we raise this error. I'm thinking this is likely a permissions issue, here's the relevant snippet of code:
https://github.com/education/classroom-assistant/blob/59d3d248b6de8789a731d15a73673f699918ba89/app/modules/submissions/actions/submission-clone.js#L27-L34

**Comment by mberasategi** [comment]
Now that I was going to answer, I've noticed I'm using a folder in the Google Drive File Stream drive. Will try again with a _local_ folder and get back.

The "container" folder and the first repository get cloned sucessfully though.

**Comment by mberasategi** [comment]
Ok, that was it 🎉 

Selecting a local drive made all repos to be cloned successfully. What is strange now is that the first one did even clone to the G File Stream drive, as I said before!

Anyway, solved. Feel free to close!

**Comment by srinjoym** [comment]
@mberasategi Glad the issue is solved! Thanks for downloading Classroom Assistant 🍎 Feel free to open up another issue if you hit any other problems.
