### ISSUE TITLE
Random fails when cloning

### ISSUE THREAD

**Issue by jtppragg** [education/classroom-assistant#110]
When downloading the repositories from an assignment many of them fail with a "Clone failed: an error has occurred" message. If I try to download them again, then the error happens again but with different repositories (random).

Sample screenshots from Classroom Assistant follow:
![screenshot_20181011_110843](https://user-images.githubusercontent.com/43606299/46795316-23669700-cd4a-11e8-84ea-53ee70f676ab.png)
![screenshot_20181011_112538](https://user-images.githubusercontent.com/43606299/46795321-282b4b00-cd4a-11e8-8f5f-648ab6b39042.png)
![screenshot_20181011_112643](https://user-images.githubusercontent.com/43606299/46795325-29f50e80-cd4a-11e8-831f-b2d7eac6bb66.png)

Not sure if this could be related to this issue https://github.com/education/classroom/issues/1586 since I also have the problem as described in my comment https://github.com/education/classroom/issues/1586#issuecomment-426581155

This is what Github Classroom web shows:
![screenshot_20181011_114310](https://user-images.githubusercontent.com/43606299/46795705-22823500-cd4b-11e8-9727-0e37fc718c9c.png)

**Comment by johndbritton** [comment]
@jtppragg Thanks for submitting this issue. Can you also provide your operating system and version information?

**Comment by jtppragg** [comment]
Hi @johndbritton, I am using Kubuntu 18.04 LTS and classroom assistant installed from the classroom-assistant_1.0.2_amd64.deb file.

**Comment by jtppragg** [comment]
Thank you @srinjoym, now GitHub Classroom Assistant is working perfectly for me. Anyway, I still suffer from this bug of GitHub Classroom https://github.com/education/classroom/issues/1586 which makes the assistant clone the wrong repository.
