### ISSUE TITLE
Create repository folders based on roster name

### ISSUE THREAD

**Issue by sigged** [education/classroom-assistant#118]
When downloading an assigment, the repositories are cloned to folders named after the GitHub username of each student.

I'm having a hard time figuring out which username belongs to which name on my roster (I'm using full names as a roster identifier). Manually renaming these folders is a pain.

It would be nice to have an option in Classroom Assistant which would create folders based on the **roster identifier**, rather than simply the GitHub username.

For example, a folder named _wizzkid8769_ (users alias on GitHub) would then become _John Doe_ (my identifier in the classroom roster).

**Comment by drynish** [comment]
I would like this request also!! I would make it a first priority.

**Comment by pisanuw** [comment]
+1 for this request. As a workaround, I am using a python script along with the roster.csv to rename all directories, but not ideal.

**Comment by d12** [comment]
I got another request for this from a teacher. I am looking into getting this solved soon.
