### ISSUE TITLE
Cannot login (using script/run)

### ISSUE THREAD

**Issue by nonZero** [education/classroom-assistant#124]
When running assistant in development from master (27d708ec6fff1456aa7cd4927342df8a060a2d47) using arch linux, after completing the two factor authentication, a blank window titled "OAuth application authorized" appears, and nothing happens.

It is not possible to work with the app.

![image](https://user-images.githubusercontent.com/66484/51604371-4726a500-1f15-11e9-94c4-65b4af6f144f.png)

These errors appear on the main window:

![image](https://user-images.githubusercontent.com/66484/51604199-adf78e80-1f14-11e9-9c5d-a079e22b3960.png)

```
/home/udi/projects/classroom-assistant/node_modules/prop-types/checkPropTypes.js:19 Warning: Failed prop type: The prop `loggedIn` is marked as required in `AppContainer`, but its value is `undefined`.
    in AppContainer (created by Connect(AppContainer))
    in Connect(AppContainer) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Routes)
    in Routes
    in div
    in Provider

/home/udi/projects/classroom-assistant/node_modules/warning/warning.js:51 Warning: You cannot PUSH the same path using hash history
```

**Comment by srinjoym** [comment]
Hi @nonZero, just responded to one of your other issues as well, Classroom Assistant has only been tested with Ubuntu 16.04 and 18.04. Refer to https://github.com/education/classroom-assistant/blob/master/docs/linux-issues.md for any other issues. We don’t have the bandwidth to add support for additional distributions right now but that might change in a month or so. Thanks!
