### ISSUE TITLE
Does Authentication work on linux?

### ISSUE THREAD

**Issue by nonZero** [education/classroom-assistant#126]
Inspecting the code, it seems that authentication requires the usage of `open-url`, but it is a feature of electron on MacOS only.

Does authentication work on Linux?
If not, how can assistant be used on linux?

**Comment by srinjoym** [comment]
Hi @nonZero 👋 Classroom Assistant is officially supported on Ubuntu 16.04 and 18.04. If you run into any issues installing on other distros, refer to https://github.com/education/classroom-assistant/blob/master/docs/linux-issues.md which has some documentation on potential fixes. Feel free to open up another issue if you hit any problems!
