### ISSUE TITLE
Cannot pull new code for student assignments

### ISSUE THREAD

**Issue by paulsmithkc** [education/classroom-assistant#164]
**Describe the bug**
I can use the Classroom Assistant client to download a snapshot of my students' assignments. However, when I try to pull down a new version of their assignment I get the following error.

`remote: The token in this link has expired. Please request another temporary clone link.`

**To Reproduce**
1. Download and Install the **Classroom Assistant** application
2. Download student repos through the client
3. Wait a few minutes
4. Attempt a `git pull` on one of the dowloaded repos.
5. The following error appears:
`remote: The token in this link has expired. Please request another temporary clone link.`

**Expected behavior**
Git should be able to successfully pull down the latest version of the student's code.

**Screenshots**
![git_token_expired](https://user-images.githubusercontent.com/6501079/72366238-7c487c00-36bf-11ea-84d5-175213142045.PNG)

**Comment by d12** [comment]
Closed in https://github.com/education/classroom/issues/2520#issuecomment-574725190

In case others run into this, the solution is in 👆
