### ISSUE TITLE
Could not find assignment (even when pressing "Download Repositories")

### ISSUE THREAD

**Issue by kingoftheconnors** [education/classroom-assistant#165]
Hello!

I am a class assistant new to Github Classroom. So far, we have had only one assignment, so I downloaded the assistant and tried grading it in Github Classroom, I pressed "Download Repositories." Two things happened.

First, it opened Github Classroom Assistant and it pasted the URL into the Select Assignment field, exactly as seen in the navbar. Apparently that's wrong because Classroom Assistant couldn't find the assignment.

Second, if Classroom Assistant isn't already open, it redirected me to the install page for the GitHub classroom assistant. So, I uninstalled it and reinstalled it. This time it doesn't redirect me, but the URL still fails. What's more, pressing "download repositories" opens the assistant, but I have to sign in again every time.

What's more, even though I have signed in, the avatar on the top-right of the screen is not my Github avatar, but a generated one as if I were new to Github (see below).

What is going on?

![image](https://user-images.githubusercontent.com/23728939/72840707-cce14b80-3c62-11ea-8fcf-491f02d30475.png)

**Comment by ddeveshh** [comment]
I'm facing the same issue. Installed github classroom assistant for the first time.
<img width="1202" alt="Screen Shot 2020-01-21 at 2 45 41 PM" src="https://user-images.githubusercontent.com/6959404/72849980-de275980-3c5c-11ea-8542-4d2c240afdbe.png">

**Comment by d12** [comment]
Something's definitely up right now, we're looking into this. I'll post an update once we have more info.

**Comment by d12** [comment]
Update: We're believe we've identified the bug, pushing a fix shortly.

**Comment by d12** [comment]
@kingoftheconnors @ddeveshh We've pushed a fix upstream, you should be all set. Thanks for the reports, and sorry for the downtime!
