### ISSUE TITLE
Command line access

### ISSUE THREAD

**Issue by fschiffers** [education/classroom-assistant#169]
Hello,
I want to use classroom-assistant remotely through a terminal and I don't have a GUI.
Is there any way to download all repos through the command line?

Best,
Florian

**Comment by jeffrafter** [comment]
At the moment there is not a way do this. It is possible to use git and write a script for it. Let us know if this is functionality you would like to see in the future.

**Comment by fschiffers** [comment]
Hi Jeff,
I have to download all the assignments on my remote machine where I don't have a GUI. To circumvent this problem, I'm now downloading all git-repos to my windows-machine and then upload them to the server.

It's not taking me too much time, but it's also not optimal. If it's not much work to implement a small command-line functionality I believe that would be appreciated by a lot of people :)
