### ISSUE TITLE
Classroom assistant crashes when logging in on macOS Big Sur

### ISSUE THREAD

**Issue by huytran1** [education/classroom-assistant#190]
I just upgraded to Big Sur (macOS Big Sur Version 11.0.1) and have had my Macbook Pro (13-inch 2016) instantly crash/restart both times I've tried use the Classroom Assistant app after entering my GitHub login information. I haven't had issues with Classroom Assistant before Big Sur.

I'm using "Classroom.Assistant-darwin-x64-2.0.2".

Is anyone else having similar issues?

**Comment by jeffrafter** [comment]
I'm looking into this now....

**Comment by huytran1** [comment]
@jeffrafter Looks like it is working now - I'm guessing there was a keychain login error or something? Thanks!
