### ISSUE TITLE
setup codesigning and create new release

### ISSUE THREAD

**Issue by shiftkey** [education/classroom-assistant#31]
Electron apps require a codesigning certificate for macOS installation, and strongly recommend this on Windows. There should be a way to do this as part of packaging, which is currently macOS-only.

Also, the updater is currently calling `http://cd-us.herokuapp.com` to look for updates. I gather that's just mirroring the GitHub releases currently on this repository, which is fine (aside from the lack of HTTPS).

**Comment by johndbritton** [comment]
> Also, the updater is currently calling http://cd-us.herokuapp.com to look for updates.

We should probably update that to a url on `classroom.github.com`. I don't know where that heroic app is or how it's running.
