### ISSUE TITLE
Allows me to proceed when downloading 0 assignments

### ISSUE THREAD

**Issue by BenEmdon** [education/classroom-assistant#71]
When I select an assignment that has 0 assignment repos, I am still able to continue with the download process:
![sep-21-2018 12-12-44](https://user-images.githubusercontent.com/11095731/45892955-b2aa0b80-bd97-11e8-98fb-8382654126df.gif)

This just seems like weird user experience to me. It would be better if we stopped the user to say that there are no repositories to download.

**Comment by johndbritton** [comment]
Either disable the button or don’t show it when there are zero repositories.

**Comment by BenEmdon** [comment]
> Either disable the button or don’t show it when there are zero repositories.

On the classroom side or the assistant side? Or both?

**Comment by johndbritton** [comment]
On the web interface. Zero case might be handled separately on desktop as well, but would start with web side.
