### ISSUE TITLE
Update README instruction on how to run on Windows 10

### ISSUE THREAD

**Issue by danielcregg** [education/classroom-assistant#87]
Please update the instructions on how to get this running on Windows 10. If you could do this in a step by step fashion that would be great. Please include required software and versions e.g. Node Version X

**Comment by ITSPaul** [comment]
There is a Windows Installer here https://github.com/education/classroom-assistant/releases. It is slow to install though

**Comment by danielcregg** [comment]
Thanks for your reply. I stumbled upon this in my search for an answer. I was trying to build the application before but I had no success. The Installer worked the first time! Please put this link on the GitHub ReadMe for Classroom Assistant and a link on the main Classroom Assistant webpage.
