### ISSUE TITLE
Application will not start on Linux Mint Cinnamon

### ISSUE THREAD

**Issue by BrianEmilius** [education/classroom-assistant#90]
I downloaded the v1.0.0 debian build and installed it on my Linux Mint Cinnamon box.

But when I try to open an assigment in classroom assistant via classroom.github.com, nothing happens.

**Comment by srinjoym** [comment]
Hi @BrianEmilius 👋 

Thanks for downloading Classroom Assistant! I'm really sorry you've hit this problem. I just released an update to Classroom Assistant which fixed some bugs users were seeing when the app was being installed on Linux. Let me know if this new build works for you!

Here's the link to the Debian package: https://github.com/education/classroom-assistant/releases/download/v1.0.1/classroom-assistant_1.0.1_amd64.deb

Thanks for your patience 🙌

**Comment by BrianEmilius** [comment]
Hi @srinjoym 
Thank you for a really fast response. I had not noticed the update which was released 5 minutes before I reported this issue.
It is now fixed for me, and everything seems to work perfectly. I am going to test as much as I can now.
Thanks for a great product :)
